### ISSUE TITLE
Folder path in get_seq.m - Minor edit needed

### ISSUE THREAD

**Issue by HANAND1979** [rozumden/tbd#2]
Hi Denys,

In the file get_seq.m, line 42, 88 and 135 could be made editable by user or maybe removed i guess since someone trying out may simply copy dataset to same folder? They are kind of set to '/mnt/lascar/rozumden/...' right now. So it gives an error when running the code. 

Thank you.

**Comment by rozumden** [comment]
Sorry about that. The idea was that people change it to their folder, that's why it's written "TODO: Change the folder for each dataset" because I don't know where you will put the dataset.
