### ISSUE TITLE
Unrecognized function or variable 'setupTemplate'.

### ISSUE THREAD

**Issue by HANAND1979** [rozumden/tbd#3]
Hi Denys,

I am using MATLAB R2020a Update 2 on Mac. When trying to run go.m, getting the following error. Can you please check. 

---Error details----
Unrecognized function or variable 'setupTemplate'.
Error in EVAL.run_tbd (line 40)
			[template m0] = setupTemplate(tdir.template);

Error in go (line 5)
EVAL.run_tbd();

**Comment by HANAND1979** [comment]
It was due to MATLAB path setup. Resolved by modifying path.

**Comment by rozumden** [comment]
I suggest running EVAL.init() first.
